### ISSUE TITLE
Bootstrap multiple angular-cli apps on the same page

### ISSUE THREAD

**Issue by dra14825** [PlaceMe-SAS/single-spa-angular-cli#1]
Hello, first of all I wanted to say that I appreciate the work that was done to integrate angular-cli apps into the single-spa project. 

Currently I am trying to bootstrap three angular-cli apps on the same page.
My problem is that only two applications get bootstrapped and the third one is producing an error.

```
single-spa-angular-cli.js:140: Cannot mount stock-root because that is not bootstrapped

While NOT_MOUNTED, 'stock' rejected its lifecycle function promise with a non-Error. This will cause stack traces to not be accurate.
```
My main.js looks like this:
```
mainRegisterApplication('user', () => import('./user-client/loader.js'), () => true).then(() => {
    registerApplication('stock', () => import('./stock-client/loader.js'),() => true);
    registerApplication('portfolio', () => import ('./portfolio-client/loader.js'), ()=> true);
});
start();
```
One thing I found out is that the last app to get bootstrapped is undefined:
`window["stock-root"]` would be undefined
I dont think it is a configuration problem in the child apps because sometimes the "stock" app works and sometimes the "portfolio" app works.
Unfortunately I cannot get behind what causes this error, because if I only start two apps they work fine on the same page.

Any help would be greatly appreciated :)

**Comment by robinComa** [comment]
Hello @dra14825 It is an issue load at same time multiple angular apps...
So I've similar issue and and fix it with the mainRegisterApplication who do a setTimeout : 
https://github.com/PlaceMe-SAS/single-spa-angular-cli/blob/master/src/utils.js#L32

It is mandatory for all apps with () => true router.

Have you try this : 
`
mainRegisterApplication('user', () => import('./user-client/loader.js'), () => true).then(() => {
    mainRegisterApplication('stock', () => import('./stock-client/loader.js'),() => true).then(() => {
         mainRegisterApplication('portfolio', () => import('./portfolio-client/loader.js'),() => true).then(() => {
              registerApplication('other-apps', () => import ('./other-apps/loader.js'), ()=> true);
         });
    });
});
start();
`
?

**Comment by robinComa** [comment]
Does it work now @dra14825 ?

**Comment by dra14825** [comment]
Thanks for the quick response @robinComa.
Unfortunately I could not try it yet, but tomorrow I will test it and tell you if it worked.

**Comment by dra14825** [comment]
I tried it and it did work after I set the timeout a little higher. Most probably my computer is too slow :).
Thanks for the help!

**Comment by robinComa** [comment]
Ok! thanks for the reply @dra14825 
Did you set the timeout inside your application with a manual setTimeout to register application or inside the single-spa-angular-cli?

Is it ok for you or do you need a timeout configuration inside single-spa-angular-cli?

**Comment by dra14825** [comment]
Actually I just copied the mainRegisterApplication function and changed the timeout to be a little bit higher.
I dont know if it should be a configuration but maybe it would be good to document this behaviour as others could have the same problem.

Thanks again for the work you have done!

**Comment by robinComa** [comment]
Could you try to use another setTimeout inside our apps declaration in order to keep the single-spa-angular-cli with the original code insi your node_modules?
Like : 
mainRegisterApplication ...
setTimeout(() => {
   mainRegisterApplication...
}, XXX);
Can I close the issue @dra14825 ?

**Comment by dra14825** [comment]
Actually I did not change the code in the node_modules just copied the function and set the timeout a little bit higher. 
Thanks for the help and yes this issue is resolved.

**Comment by robinComa** [comment]
Hello @dra14825 I just realase a new version of single-spa-angular-cli and this issuer is now solved : 
https://www.npmjs.com/package/single-spa-angular-cli

You can do this directly (without register main app) : 
```
const LOADER = {
    menu: import('./loaders/menu.js'),
    home: import('./loaders/home.js'),
    app1: import('./loaders/app1.js'),
    help: import('./loaders/help.js')
};

registerApplication('menu', () => LOADER.menu, singleSpaAngularCliRouter.hashPrefix('/**', true));
registerApplication('home', () => LOADER.home, singleSpaAngularCliRouter.hashPrefix('/home', true));
registerApplication('app1', () => LOADER.app1, singleSpaAngularCliRouter.hashPrefix('/app1'));
registerApplication('help', () => LOADER.help, singleSpaAngularCliRouter.hashPrefix('/app1'));
start();
```

Take care about breaking changes : 
```
// src/loaders/app1.js

import singleSpaAngularCli from 'single-spa-angular-cli';

const lifecycles = singleSpaAngularCli({
    **name: 'app1',**
    selector: 'app1-root',
    baseScriptUrl: '/src/apps/app1/dist',
    **css: [
        'styles.bundle.css',
    ],**
    scripts: [
        'inline.bundle.js',
        'polyfills.bundle.js',
        'vendor.bundle.js',
        'main.bundle.js'
    ]
});

export const bootstrap = [
    lifecycles.bootstrap
];

export const mount = [
    lifecycles.mount
];

export const unmount = [
    lifecycles.unmount
];

**export const unload = [
    lifecycles.unload
];**
```

**Comment by dra14825** [comment]
@robinComa  Tahnks again for your work, I appreciate it

**Comment by DarkKnight1992** [comment]
i am facing this error on the latest angular-cli only the first app mounts whenever i try to mount another application i get this error 

![image](https://user-images.githubusercontent.com/15063261/42448056-91270496-8399-11e8-958d-e7f724f193fd.png)

I also tried adding a settimeout in the second application still the result, Cannot mount app because that is not bootstraped

**Comment by robinComa** [comment]
Hello, could you send your prodducts loader please?

**Comment by DarkKnight1992** [comment]
```javascript 

import { loader } from 'single-spa-angular-cli';

const lifecycles = loader({
    name: 'prodducts',
    selector: 'prodducts-root',
    baseHref: '/prodducts'
});

export const bootstrap = [
    lifecycles.bootstrap
];

export const mount = [
    lifecycles.mount
];

export const unmount = [
    lifecycles.unmount
];

export const unload = [
    lifecycles.unload
];

```

**Comment by robinComa** [comment]
Do you start prodducts with ng serve or do you build it to run as build package?

**If ng serve :** 
make sure you have a webpack config to to it : 
add a line with your app as : [webpack.config.js](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/webpack.config.js#L9)

If you choose the 4201 port for exemple, start you ng serve with --port 4201

**If you start a builded version :** 

Make sure you build it with the correct base href inside your [build task](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/package.json#L9)
And comment all the line on your [webpack.config.js](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/webpack.config.js#L9)

can that help you?

**Comment by DarkKnight1992** [comment]
i am using ng server for right now prodducts in running on default port and cart is running on 4201

webpack config

```javascript
const webpack = require('webpack');
const path = require('path');
const applications = require('./bootstrapper/applications.config.json');

const PORT = 8080;

const devApplications = {
  prodducts: 'http://localhost:4200',
  cart: 'http://localhost:4201',
  // app1: 'http://localhost:4202',
  // help: 'http://localhost:4203'
};

module.exports = {
  entry: [
    __dirname + '/bootstrapper/main.js',
    __dirname + '/bootstrapper/main.css'
  ],
  output: {
    path: process.cwd() + '/build',
    filename: '[name].js',
    publicPath: '/build/',
  },
  devtool: 'inline-source-map',
  devServer: {
    port: PORT,
    publicPath: '/build/',
    contentBase: './',
    historyApiFallback: true,
    proxy: getProxyConfig(applications, devApplications),
  },
  resolve: {
    modules: [
      'node_modules',
      path.resolve(__dirname, './'),
    ],
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.html$/,
        exclude: /node_modules/,
        loader: 'html-loader',
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: getBabelConfig(),
      }
    ],
  }
};

function getBabelConfig() {
  return {
    presets: [
      ['babel-preset-env', {
        targets: {
          'browsers': ['last 2 versions'],
        },
      }],
    ],
    plugins: [
      'transform-object-rest-spread',
      'transform-class-properties',
      'syntax-dynamic-import',
      'transform-function-bind',
    ],
  };
}
function getProxyConfig(applications, devApplications) {
  const proxy = {};
  for (app of applications) {
    const path = app.baseHref + '/';
    let target = `http://localhost:${PORT}/build/${path}`;
    if (devApplications.hasOwnProperty(app.name)) {
      target = devApplications[app.name];
    }
    proxy[path] = {
      target: target,
      pathRewrite: {
        [path]: ''
      },
      bypass: function (req, res, proxyOptions) {
        if (req.headers.accept.indexOf('html') !== -1) {
          return '/index.html';
        }
      }
    };
  }
  return proxy;
}
/**
function getProxyConfig(applications, devApplications) {
  const proxy = {};
  for (const appName of Object.keys(devApplications)) {
    const application = applications.find(a => a.name === appName);
    const path = application.baseHref + '/';
    proxy[path] = {
      target: devApplications[appName],
      pathRewrite: {
        [path]: ''
      },
      bypass: function (req, res, proxyOptions) {
        if (req.headers.accept.indexOf('html') !== -1) {
          return '/index.html';
        }
      }
    };
  }
  return proxy;
}
 */

```

**Comment by robinComa** [comment]
Do you declare the app base ref like [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/apps/home/src/app/app-routing.module.ts#L25) ?

**Comment by DarkKnight1992** [comment]
I can create a git repo i you wanna check it out ?

**Comment by robinComa** [comment]
ok...

Could you send to me your network please, maybe a 404 on the index.html of the prodduct app?

**Comment by DarkKnight1992** [comment]
"Could you send to me your network please" what you mean by that ?

I as mentioned prodduct app and cart app both work as long as they are registered as the first app

**Comment by robinComa** [comment]
On your chrome console, the network tab

**Comment by DarkKnight1992** [comment]
same error if prodducts is registered first

```javascrtipt 
registerApplication(
	'prodducts',
	() => LOADER.prodducts,
	() => true
)

setTimeout(
	registerApplication(
		'cart',
		() => LOADER.cart,
		() => true
	), 300

)
```
![image](https://user-images.githubusercontent.com/15063261/42450717-ba26698c-83a2-11e8-84b4-7fb2aa1a0ecf.png)

![image](https://user-images.githubusercontent.com/15063261/42450737-c3982b2c-83a2-11e8-9280-7cab3a29f4c7.png)

**Comment by robinComa** [comment]
Hoo ok I understand! You want display both apps in same time?

**Comment by DarkKnight1992** [comment]
thats correct

**Comment by robinComa** [comment]
You can test with the match route as [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/portal/main.js)

In my sample, home and help could be both present on a page, one with a path name, other by query params.

**Comment by DarkKnight1992** [comment]
i would like to use the menu and app example  but sadly it doesn't work either

**Comment by DarkKnight1992** [comment]
```javascript 
[
    {
        "name": "cart",
        "selector": "cart-root",
        "baseHref": "/cart",
        "matchRoute": "/**"
    },
    {
        "name": "prodducts",
        "selector": "prodducts-root",
        "baseHref": "/prodducts",
        "matchRoute": "/prodducts",
        "isDefaultApp": true
    }
]
```
```javascript
import { registerApplication, start } from 'single-spa';
import { loader, router } from 'single-spa-angular-cli';
import 'babel-polyfill';
import 'zone.js';

const applications = require('./applications.config.json');

for (const application of applications) {
    registerApplication(
        application.name,
        (() => {
            const lifecycles = loader({
                name: application.name,
                selector: application.selector,
                baseHref: application.baseHref
            });
            return {
                bootstrap: [lifecycles.bootstrap],
                mount: [lifecycles.mount],
                unmount: [lifecycles.unmount],
                unload: [lifecycles.unload],
            };
        })(),
        router.matchRoute(application.matchRoute, application.isDefaultApp)
    );
}

start();
```

![image](https://user-images.githubusercontent.com/15063261/42451452-f492feda-83a4-11e8-96f2-af8f3ea72c89.png)

![image](https://user-images.githubusercontent.com/15063261/42451466-fd58b5e6-83a4-11e8-9dc8-2c32413631b5.png)

**Comment by DarkKnight1992** [comment]
url is http://localhost:8080/prodducts

**Comment by robinComa** [comment]
Your network is filter by JS, please click on all tab
Could you try with a /  : 
"matchRoute": "/prodducts/",  ?

**Comment by DarkKnight1992** [comment]
![image](https://user-images.githubusercontent.com/15063261/42452452-a6316440-83a7-11e8-907d-b72c4bc5242f.png)

**Comment by DarkKnight1992** [comment]
same response with /prodducts/ 

![image](https://user-images.githubusercontent.com/15063261/42452512-d74ce216-83a7-11e8-8360-98bf83877210.png)

**Comment by DarkKnight1992** [comment]
![image](https://user-images.githubusercontent.com/15063261/42452546-f13a535c-83a7-11e8-8f5c-a44bcb25ce23.png)

**Comment by robinComa** [comment]
Ok... I have no more ideas...
Could you share your repo?
I don't know when but I will try to run your app

**Comment by DarkKnight1992** [comment]
https://github.com/DarkKnight1992/ng-spa

**Comment by hichauhan** [comment]
I am trying to register an angular-cli app inside a react app but I am getting following error, even after trying everything:

![image](https://user-images.githubusercontent.com/41266982/45586417-bc092300-b914-11e8-8294-630e09f69aab.png)


Here's my code

```index.js (single-spa-config)```
```
import registerServiceWorker from './registerServiceWorker';
import {registerApplication, start} from 'single-spa';


registerApplication(
  'menu',
  () => import('./menu/menu.app'),
  () => true
)

registerApplication(
  'home',
  () => import('./home/home.app'),
  () => true
)

start();
registerServiceWorker();
```

```home.app.js```
```
import { loader } from 'single-spa-angular-cli';

const lifecycles = loader({
    name: 'home',
    selector: 'app-root',
    baseHref: '/home',
    container: '#app'
});

export const bootstrap = [
    lifecycles.bootstrap
];

export const mount = [
    lifecycles.mount
];

export const unmount = [
    lifecycles.unmount
];

export const unload = [
    lifecycles.unload
];
```

I also built my angular app using:
```
ng build --prod --output-path ../../public/
```

---

I am using angular-cli version 6.1.0 and react version 16.5.1
