### ISSUE TITLE
Child application not bootstraped

### ISSUE THREAD

**Issue by Kotohitsu** [PlaceMe-SAS/single-spa-angular-cli#11]
single-spa: 3.9.0
single-spa-angular-cli: 0.4.0

The child apps of my application are still not mounted with the error 
`Cannot mount menu because that is not bootstraped`,
but all files are loaded.

I think the child apps are not mounted because they do not appear in the `window.singleSpaAngularCli`.

Could you tell me where they should be added so I can research what's going wrong?

**Comment by robinComa** [comment]
What is the value of window.singleSpaAngularCli?
undefined, {} ?

**Comment by Kotohitsu** [comment]
The value is:
``` javascript
{
    isSingleSpa: true
}
```

**Comment by Kotohitsu** [comment]
Yes I'm using the app name like in the example

**Comment by joeldenning** [comment]
This project is deprecated (see #36). Use [single-spa-angular@3](https://github.com/CanopyTax/single-spa-angular/), instead.
