### ISSUE TITLE
Start the child application in a specified div

### ISSUE THREAD

**Issue by frezelth** [PlaceMe-SAS/single-spa-angular-cli#12]
Hi,

Thanks a lot for your lib, I tried to use it and it works very well.
I have a use case where I would like to start the children apps in a particular div instead of putting it below the menu.
Would you know if it would be doable? Basically instead of the "menu" app I would like to have some kind of "template" with header/menu/footer and I would like my child app to load between the menu and footer.

Thanks for any suggestion!

Thomas

**Comment by robinComa** [comment]
Hello @frezelth happy to see you like single-spa-angular-cli!
I think your issue would be solved by CSS tricks.

Your <header>, <nav>, <footer> tags on your "layout" app, would fixed CSS position at top, left, 
After it, your child-root would be manage margin top (for the header), ... to let place to the "layout" app components.

What are do think about this approch?

**Comment by frezelth** [comment]
I'll try it this way, thanks, I'll keep you informed.

**Comment by sergiomcalzada** [comment]
Hello, I need that too. I had a "child" app that acts as layout and it is always visible, but instead of being a simple menu is a big layout and need to load child apps inside that layout.

Maybe and option and a change in https://github.com/PlaceMe-SAS/single-spa-angular-cli/blob/master/src/loader/index.ts#L38

**Comment by robinComa** [comment]
Hello @sergiomcalzada , I understand, the best way is to provide to you a solution to implement your own getContainerEl function?

Regards,

**Comment by sergiomcalzada** [comment]
Hello @robinComa , that could be a solution. I started a fork and change the getContainerEl function to check for an optional "container selector" and, if present, use it to get the html container to use instead the document.body.

https://github.com/sergiomcalzada/single-spa-angular-cli/commit/a793563f6eda9ee0e7d199b13e93dedc6bca1d27

**Comment by robinComa** [comment]
Is it working for you with this update? If yes, could you propose a PR?

**Comment by sergiomcalzada** [comment]
Not tested yet, when I test it i send the PR

**Comment by sergiomcalzada** [comment]
Pull request created #16
