### ISSUE TITLE
Compatibility with IE11

### ISSUE THREAD

**Issue by frezelth** [PlaceMe-SAS/single-spa-angular-cli#13]
Hi,

Do you foresee a compatibility with IE11 ? Right now it seems that it does not fully work.
I tried the examples and I get an error when navigating to app1 from the home app:

![image](https://user-images.githubusercontent.com/8929828/37717564-152f5cfe-2d21-11e8-8173-bf8decc2a0ec.png)

Thanks!

**Comment by robinComa** [comment]
Hello @frezelth , yes I don't tst it on IE... sorry for that.
I know the issue, I'm using remove() on a DOM ele and it is not supported by IE.
I fix it this week, thanks for information!
I go back to you when it will be fixed
