### ISSUE TITLE
[Tip] Font styles not working on remote app

### ISSUE THREAD

**Issue by sergiomcalzada** [PlaceMe-SAS/single-spa-angular-cli#17]
When you import some kind of font in angular-cli.json/styles section and run ng on development mode, it generates an script that inject the <style> tags on runtime. That causes that the font are not loaded.

You need to force the "styles.css" files to be generated. For solve that problem, the command must be run with the "extractCss" modifier:

```
ng serve  --extractCss
```

**Comment by robinComa** [comment]
Thanks @sergiomcalzada
