### ISSUE TITLE
Pass dynamic base url to Angular app

### ISSUE THREAD

**Issue by freon27** [PlaceMe-SAS/single-spa-angular-cli#19]
Hi,

I'm trying to solve a problem where an application may pre-configure some variables before linking to the child app, providing the selections via the path. So the child app would be routed something like this:

`/:variable1/:variable2/my-child-app`

Doing the matching is not problem but, the issue is that the `APP_BASE_HREF` in my angular apps needs to be dynamic and the Angular app needs access to the variables matched by the wildcards. 

Is there any way of passing information into the Angular app when loading it? I'm not sure if this is the sort of thing that props can be used for? I took a look but I couldn't see a way to use them like this. I could use local/session storage but I thought maybe there was a cleaner way via single-spa[-angular-cli].

Thanks

**Comment by freon27** [comment]
Obviously in this case I could take the first two parts of the path but I'd like my child app not to have to know about where it is until it's loaded.

**Comment by robinComa** [comment]
Hello @freon27, I undersand the issue, the variable are in use on the main portal app or inside the my-child-app? Or both?

**Comment by freon27** [comment]
They would be used inside the child apps. To be honest, since I asked the question I've fed this back to management as not possible (or at least something we shouldn't do).  It feels very messy (although I would still be interested to know how one might pass context information to child apps when they are loaded)

**Comment by joeldenning** [comment]
This project is deprecated (see #36). Use [single-spa-angular@3](https://github.com/CanopyTax/single-spa-angular/), instead.
