### ISSUE TITLE
getAppNames undefined while loading angular cli application

### ISSUE THREAD

**Issue by mkmurali** [PlaceMe-SAS/single-spa-angular-cli#22]
I have cloned single-spa-examples and created a fresh new angular-cli application called ngtest in a subfolder ngtest in src folder.  Installed npm package single-spa-angular-cli and created a loader file 
```typescript
import { loader } from 'single-spa-angular-cli';

const lifecycles = loader({
  name: 'ngtest',
  selector: 'app-root',
  baseHref: '/ngtest'
});

export const bootstrap = [lifecycles.bootstrap];

export const mount = [lifecycles.mount];

export const unmount = [lifecycles.unmount];

export const unload = [lifecycles.unload];
```
single-spa configuration to define child application is as follows
```typescript
declareChildApplication(
  'ngtest',
  () => import('./ngtest/angular.app.js'),
  pathPrefix('/ngtest')
);
```

When I try to load this app, I see the following error.
![image](https://user-images.githubusercontent.com/763436/43030817-790c3e60-8c5b-11e8-8ef8-8cd5f26b3711.png)

It appears, the loader is failing to get a reference to the root singlespa application. But could not figure out why. Any ideas?

**Comment by mkmurali** [comment]
@robinComa I have tried again, this time after making changes as in those steps.  Still see the exact same error.  Please note that my base project is https://github.com/CanopyTax/single-spa-examples repo.

**Comment by robinComa** [comment]
Hello,

What is the version of SingleSpa?
getAppNames is a SingleSpa function used [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli/blob/master/src/loader/index.ts#L49)

**Comment by bfaulk96** [comment]
I get this error as well, with SingleSpa 4.0.0. Could this be related to Webpack 4 changes?

**Comment by bfaulk96** [comment]
After editing some files, it appears that my `Cannot read property 'getAppNames' of undefined came from the `noLoadingApp` function in loader/index.ts (well, index.js after compiling)

**Comment by bfaulk96** [comment]
I think I've further narrowed down the source of the issue:
```
const bootstrap = (opts: Options, props: any) => {
    window.singleSpaAngularCli.isSingleSpa = true;
    const { singleSpa } = props
    return new Promise((resolve, reject) => {
        onNotLoadingApp(opts.name, singleSpa).then(() => {
            loadAllAssets(opts).then(resolve, reject);
        }, reject);
    });
};
```
one the third line, props.singleSpa is undefined and breaks the rest

**Comment by mkmurali** [comment]
@bfaulk96 @robinComa Thank you very much.

**Comment by bfaulk96** [comment]
Did the new version of Single-Spa (4.0.1) fix it for you? If so, @robinComa can close this issue

**Comment by mkmurali** [comment]
Yes, it fixed the issue. Closing it.
