### ISSUE TITLE
Update to Angular 6/Webpack 4

### ISSUE THREAD

**Issue by bfaulk96** [PlaceMe-SAS/single-spa-angular-cli#23]
This library is currently out-of-date with Angular 6. While I understand some teams haven't updated to Angular 6, it might be useful for those of us that have to have a release tagged as such.

**Comment by bfaulk96** [comment]
One thing in particular that stands out: As long as this is used within a project currently, Angular 6 projects have to use the `rxjs-compat` library to support the rxjs version that this library is stuck on.

**Comment by joeldenning** [comment]
This project is deprecated (see #36). Use [single-spa-angular@3](https://github.com/CanopyTax/single-spa-angular/), instead.
