### ISSUE TITLE
Make Load Timeout Configurable

### ISSUE THREAD

**Issue by bfaulk96** [PlaceMe-SAS/single-spa-angular-cli#24]
Currently, the timeout for app mounting is 3 seconds. For large apps (like the ones my company is trying to mount), 3 seconds is not necessarily enough time. Because of this, it times out and never mounts the child apps. I would like a way to configure this timeout when initially loading the app.

**Comment by bfaulk96** [comment]
I should note, the mounting timeout is configurable in Single-Spa, so why is it hardcoded in the loader/index.ts of single-spa-angular-cli? (the `onNoteLoadingApp()` function has the line `if (time >= 3000`)

**Comment by robinComa** [comment]
thanks guys!
