### ISSUE TITLE
Mount function Promise to return Module instance

### ISSUE THREAD

**Issue by dra14825** [PlaceMe-SAS/single-spa-angular-cli#3]
Hello,
I again got an Issue that I cannot solve.
I watend to pass customProperties into the child application. 
I wanted to do something like this:
https://github.com/me-12/single-spa-portal-example/blob/453296e7892fceb9820e915da534db8600142e71/app2Angular4/src/app2.js#L21
Unfortunately when I try to use the result of the Promise it is allways undefined, I think it is because the Promise gets resolved and not reference to the mounted module is returned:
https://github.com/PlaceMe-SAS/single-spa-angular-cli/blob/a65eb53cbe8738fbf250932fcfc33279a17045ea/src/single-spa-angular-cli.js#L50

Is there a way how to pass customProperties into an angular-cli single-spa application?

Again thanks any help.

**Comment by robinComa** [comment]
Hello @dra14825 ,
I understand your issue, I wanted to fix it now but it's harder than I thought.
I hope I will propose to you a new version this week.
Regards,
