### ISSUE TITLE
v0.4.2 doesn't support Angular 6/ Single-Spa 4.0+

### ISSUE THREAD

**Issue by bfaulk96** [PlaceMe-SAS/single-spa-angular-cli#30]
For Angular 6 (or, more specifically, Webpack 4), chunking was dramatically changed. Instead of each bundle containing a global function call to a `webpackJsonP()` function, Webpack 4 restructured the webpackJsonP to be a global array object. Because of this, the runtime chunks no longer have to be executed first, and scripts can be loaded asynchronously.

What this means:
While I wish I understood the last sentence more, I don't. What I do know is that because of the changes to Webpack 4, the chunks of the first child app are successfully added to the DOM, but any subsequent apps just re-load the first child app because the chunks are not unique. This is unrelated to bundle names; you can still hash the bundle names with Angular 6 and the scripts are loaded with different names, but the underlying chunks still cause issues.

<img width="940" alt="screen shot 2018-08-01 at 9 53 15 am" src="https://user-images.githubusercontent.com/12897328/43529405-d451f800-9570-11e8-9510-f6ac1825da54.png">

In the image above, the curly braces represent the chunk names (i.e. {scripts} and {0} are the "scripts" chunk and an unnamed chunk due to 'optimization' being set in the `angular.json` config file) Since every app has a 'scripts' chunk, even though the file hashes are different, it uses the first 'scripts' chunk loaded onto the DOM.

**Comment by joeldenning** [comment]
This project is deprecated (see #36). Use [single-spa-angular@3](https://github.com/CanopyTax/single-spa-angular/), instead.
