### ISSUE TITLE
Not bootstraped - child application

### ISSUE THREAD

**Issue by damian1717** [PlaceMe-SAS/single-spa-angular-cli#31]
Child app:
Angular CLI: 6.1.5
Node: 8.11.3
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.5
@angular-devkit/core         0.7.5
@angular-devkit/schematics   0.7.5
@schematics/angular          0.7.5
@schematics/update           0.7.5
rxjs                         6.2.2
typescript                   2.9.2

The child apps of my application are still not mounted with the errors:

1.Cannot mount app2 because that is not bootstraped
2.Error: Uncaught (in promise): [object Undefined]
3.Uncaught Error: 'app2' died in status NOT_MOUNTED: undefined

I did everything according to the documentation.
You have some suggestions for me what is wrong.
What's going wrong?

**Comment by joeldenning** [comment]
Hmm I'm not sure what that would be caused by. @robinComa any ideas?

@damian1717  could you provide a minimal reproduction case for this?

**Comment by joeldenning** [comment]
This project is deprecated (see #36). Use [single-spa-angular@3](https://github.com/CanopyTax/single-spa-angular/), instead.
