### ISSUE TITLE
Please make me a maintainer to this project

### ISSUE THREAD

**Issue by joeldenning** [PlaceMe-SAS/single-spa-angular-cli#32]
Hi @robinComa -- thanks again for all of your help with this project. Could you make me a contributor on github for this project? And also the ability to publish to npm?

I'm hoping to be able to help out more with the issue queue and maintenance of this project.

**Comment by robinComa** [comment]
Hello @joeldenning , yes, non problem :-)

**Comment by robinComa** [comment]
I added you to : 
- https://github.com/PlaceMe-SAS/single-spa-angular-cli
- https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples
- https://www.npmjs.com/package/single-spa-angular-cli

Thanks for your help
