### ISSUE TITLE
Look like does not work with Angular 6+

### ISSUE THREAD

**Issue by DmitriyLitvinov** [PlaceMe-SAS/single-spa-angular-cli#34]
I cloned this repository and updated dependencies:
```
"single-spa": "4.0.1",
    "single-spa-angular-cli": "0.4.2",
```
Works fine. but if I try to add new sub-project (angular 6+) I have some troubles with the build single-spa application
```
Uncaught TypeError: Cannot read property 'bind' of undefined
    at bootstrap:141
    at bootstrap:149
(anonymous) @ bootstrap:141
(anonymous) @ bootstrap:149
```
Seems like the single-spa does not work with Angular 6+, because if I downgrade sub-application to the Angular 5 the single-spa application works fine.

Any idea how to use single spa with angular 6+ ?

**Comment by chriskitson** [comment]
Same for me!

**Comment by geradev** [comment]
same here

**Comment by valeriopisapia** [comment]
I developed a boilerplate in Angular 6 (without Angular-CLI) which includes the single-spa configuration.  It works well with single-spa and you can integrate with single-spa-cli as well.
https://github.com/valeriopisapia/angular6-boilerplate
Let me know if it's helpful for you.

**Comment by joeldenning** [comment]
This project is deprecated (see #36). Use [single-spa-angular@3](https://github.com/CanopyTax/single-spa-angular/), instead. It has support for Angular 6, 7, and 8
