### ISSUE TITLE
dependency of rxjs is out of dated

### ISSUE THREAD

**Issue by nickfeng1982** [PlaceMe-SAS/single-spa-angular-cli#35]
single-spa-angular already has the rxjs dependency updated to 6.0.0, however, the single-spa-angular-cli only supports 5.5.6 so far. That affects Angular 6/7 app if we are going to use this framework to build micro-front ends services. Any thoughts or help on this issue?

**Comment by joeldenning** [comment]
This project is deprecated (see #36). Use [single-spa-angular@3](https://github.com/CanopyTax/single-spa-angular/), instead.
