### ISSUE TITLE
regression: error on app unmount after last release

### ISSUE THREAD

**Issue by orlandodemauro** [PlaceMe-SAS/single-spa-angular-cli#6]
hi @robinComa 

upgrating to the last version is producing the following error:

> Unhandled Promise rejection: unloadApplication requires a string 'appName' ; Zone: <root> ; Task: Promise.then ; Value: Error: unloadApplication requires a string 'appName'

it is related to 
https://github.com/PlaceMe-SAS/single-spa-angular-cli/blob/dde7a22e1f7351d4a7b5fe97876973c2b042bda4/src/single-spa-angular-cli.js#L68 introduced by
https://github.com/PlaceMe-SAS/single-spa-angular-cli/pull/5.

the fastes workaround is to add the appName as name property of the loader config object, and it is fine when the loader.js is in the parent. (one loader.js file for each children in the parent)

the workaround above is not valid when we want to deploy the children separately and bundle the loader with it. in this case the appName defined in the parent should be totally transparent to the children.

A possible use case is when the same app is loaded at different routes:

```
mainRegisterApplication("app2", () => SystemJS.import("http://localhost:4200/loader.js"), singleSpaAngularCliRouter.hashPrefix("/app2", true));

mainRegisterApplication("app3", () => SystemJS.import("http://localhost:4200/loader.js"), singleSpaAngularCliRouter.hashPrefix("/app3", true));
```

any suggestion? thank you so much

**Comment by robinComa** [comment]
Hooooo yes sorry, I forgot to update the doc... my bad...
Since this version you have to register an unload function on your loader as : 
export const unmount = [
    lifecycles.unload 
];
This is an additional feature from @Kotohitsu (tx u) and it solve one bug with multiple lazy loading of module.

Sorry for that @orlandodemauro 
Does it works now?
I will update the doc next time, I have no time for the moment...

**Comment by robinComa** [comment]
I've just updated the doc (not yet on npm):
https://github.com/PlaceMe-SAS/single-spa-angular-cli

**Comment by orlandodemauro** [comment]
@robinComa  thank you so much for your quick response. I registered the unload function but i´m still getting the error

> nhandled Promise rejection: unloadApplication requires a string 'appName' ; Zone: <root> ; Task: Promise.then ; Value: Error: unloadApplication requires a string 'appName'

the opt.name is undefined and when passed to single-spa.unloadApplication

**Comment by robinComa** [comment]
My bad too... 
I re update the [doc ](https://github.com/PlaceMe-SAS/single-spa-angular-cli/blob/master/README.md
)
const lifecycles = singleSpaAngularCli({
    **name: 'app1',**
    selector: 'app1-root',
    baseScriptUrl: 'http://localhost:4202',
    scripts: [
        'inline.bundle.js',
        'polyfills.bundle.js',
        'styles.bundle.js',
        'vendor.bundle.js',
        'main.bundle.js'
    ]
});

**Comment by orlandodemauro** [comment]
so the same app cannot be loaded twice now? Any suggestion on how implement the following scenario?

```
mainRegisterApplication("app2", () => SystemJS.import("http://localhost:4200/loader.js"), singleSpaAngularCliRouter.hashPrefix("/app2", true));

mainRegisterApplication("app3", () => SystemJS.import("http://localhost:4200/loader.js"), singleSpaAngularCliRouter.hashPrefix("/app3", true));
```

**Comment by orlandodemauro** [comment]
addinf name:"app2" i´m getting 

> Unhandled Promise rejection: Could not unload application 'app2' because no such application has been declared ; Zone: <root> ; Task: Promise.then ; Value: Error: Could not unload application 'app2' because no such application has been declared

**Comment by robinComa** [comment]
Hoooo ok, I know this issue, I solve it with a wainting between 2 loads : 
mainRegisterApplication("app2", () => SystemJS.import("http://localhost:4200/loader.js"), singleSpaAngularCliRouter.hashPrefix("/app2", true)).then(() => {
mainRegisterApplication("app3", () => SystemJS.import("http://localhost:4200/loader.js"), singleSpaAngularCliRouter.hashPrefix("/app3", true));
});

**Comment by robinComa** [comment]
add then on your preferd app and load the other one inside the callback

**Comment by orlandodemauro** [comment]
sorry i haven´t been clear. let assume that I add name:"app2" to my loader.js.
Then I´ll register two apps one called app2 and one called app3, importing the same loader. 
When the app3 will be unloaded, the single-spa.unloadApplication method will be called with opt.name="app2". am I right?

**Comment by orlandodemauro** [comment]
regarding the error 

> Unhandled Promise rejection: Could not unload application 'app2' because no such application has been declared ; Zone: ; Task: Promise.then ; Value: Error: Could not unload application 'app2' because no such application has been declared

I´m already loading the apps synchronously and I´m getting the error when the app is unloaded ( when i change the route).

**Comment by robinComa** [comment]
Hoo yes that right, for this case you have to register 2 different loaders but I dont thonk that you could load 2 same apps because that the same angular module with the same root tag.
Try it and let me know

**Comment by orlandodemauro** [comment]
yes you are totally right. the root-tag could be passed as customProps to the module by the parent, I know there is an issue to track the customProps feature. 

BTW the load of two apps is secondary, the real problem is that adding the name property and registering the unload method I'm still getting the error

> Unhandled Promise rejection: Could not unload application 'app2' because no such application has been declared ; Zone: <root> ; Task: Promise.then ; Value: Error: Could not unload application 'app2' because no such application has been declared

and here the array got with getAppsName:  ["menu", "home", "app2", "app1", "app3"]

**Comment by robinComa** [comment]
Why do your load 2 times the same app on your screen?

**Comment by robinComa** [comment]
Could you try to load the second one inside the first promise callback please? as : 

```
mainRegisterApplication("app2", () => SystemJS.import("http://localhost:4200/loader.js"), singleSpaAngularCliRouter.hashPrefix("/app2", true)).then(() => {
     // here load the second
});
```

**Comment by orlandodemauro** [comment]
I´m already doing it, I´m getting the config from a json file and registering the apps with a syncEach:

```
    eachSeries(appStructure.items, async (element, callback) => {
        const { appName, appUrl, route } = element;

        mainRegisterApplication(appName, () => SystemJS.import(appUrl), singleSpaAngularCliRouter.hashPrefix(route, true)).then(() => {
            callback();
        });
    }, err => {
        if (err) console.log('Is not possible to mount the apps', err);
        console.log(getAppNames());
    });
```

**Comment by orlandodemauro** [comment]
here the json

```
{
    "elements": 5,
    "items": [
        {
            "appName": "menu",
            "appUrl": "http://localhost:4200/loader.js",
            "route": "/**"
        },
        {
            "appName": "home",
            "appUrl": "http://localhost:4201/loader.js",
            "route": "/home"
        },
        {
            "appName": "app2",
            "appUrl": "http://localhost:4203/loader.js",
            "route": "/app2"
        },
        {
            "appName": "app1",
            "appUrl": "http://localhost:9001/main.js",
            "route": "/app1"
        },
        {
            "appName": "app3",
            "appUrl": "http://localhost:9002/main.js",
            "route": "/app2"
        }

    ]
}
```

**Comment by orlandodemauro** [comment]
how you can see I´m not loading anymore the same app twice on the screen, but i´m still getting the error :(

**Comment by robinComa** [comment]
I don't understand why you load for exemple for /app2 2 files : 
- http://localhost:4203/loader.js
- http://localhost:9002/main.js

http://localhost:9002/main.js is not a loader

**Comment by orlandodemauro** [comment]
in my case http://localhost:9002/main.js is a react app and the main is a loader even if the name is not loader.js

**Comment by orlandodemauro** [comment]
with single-spa is possible to load two apps on the same page, this is one of the good things. you can have a menu that is always present on the page and then load different apps based on the needs. the issue is related to the single-spa.unloadApplication in single-spa-angular-cli. looks like that getAppNames() returns an empty array when called inside single-spa-angular-cli

**Comment by robinComa** [comment]
Ok I understand now, For my case I only create the /** to display 2 apps on same page for (all the page) but not for an url...
I don't know getAppNames() od single spa, could you tell me more about it?

**Comment by robinComa** [comment]
Maybe I have to add unloadApplication(opts.name, {waitForUnmount: true});
What do you think about it?

**Comment by orlandodemauro** [comment]
the getAppNames return all the apps registered

```
export function getAppNames() {
  return apps.map(toName);
}
```


the unloadApplication called in single-spa-angular-cli has this code

```
export function unloadApplication(appName, opts={waitForUnmount: false}) {
  if (typeof appName !== 'string') {
    throw new Error(`unloadApplication requires a string 'appName'`);
  }
  const app = find(apps, App => App.name === appName);
  if (!app) {
    throw new Error(`Could not unload application '${appName}' because no such application has been declared`);
  }
```

the apps variable is [] when called by single-spa-angular-cli inside a children app.  

but when i call getAppNames from the parent main ( were i define all the children) i´m getting the real array of apps ["menu", "home", "app2", "app1", "app3"]

**Comment by orlandodemauro** [comment]
I can confirm that adding the check, the error is gone. the apps array is not global, so it is not shared between the parent and the children apps. calling unloadApplication in a children does not use the same apps array defined in the main app where the apps are registered. @joeldenning any clue?

**Comment by robinComa** [comment]
@orlandodemauro I just push a new version [0.1.12](https://www.npmjs.com/package/single-spa-angular-cli)
- Better register apps
- split load files : css & js

see the documentation of the exemple : 
[https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples)

You can now register directly with single spa register application : 
registerApplication('menu', () => LOADER.menu, singleSpaAngularCliRouter.hashPrefix('/**', true));
registerApplication('home', () => LOADER.home, singleSpaAngularCliRouter.hashPrefix('/home', true));
registerApplication('app1', () => LOADER.app1, singleSpaAngularCliRouter.hashPrefix('/app1'));
registerApplication('help', () => LOADER.help, singleSpaAngularCliRouter.hashPrefix('/app1'));
start();

I simulate your case with a help apps who is loaded at same time than app1

Let me know!

**Comment by orlandodemauro** [comment]
@robinComa thank you so much for you work. but unfortunately this new version is totally breaking the app:

```
    registerApplication('menu', () => SystemJS.import("http://localhost:4200/loader.js"), singleSpaAngularCliRouter.hashPrefix('/**', true));
    registerApplication('home', () => SystemJS.import("http://localhost:4201/loader.js"), singleSpaAngularCliRouter.hashPrefix('/home', true));
    registerApplication('app1', () => SystemJS.import("http://localhost:9001/main.js",), singleSpaAngularCliRouter.hashPrefix('/app2',));
    registerApplication('app2', () => SystemJS.import("http://localhost:4203/loader.js"), singleSpaAngularCliRouter.hashPrefix('/app2',));
    start();
```

menu, home and app2 are angularCli apps
app1 is a react app

here a summary of the issues with the single-spa-cli different versions:

version 1.10: able to load and unload apps with any issue
version 1.11: able to load multiple apps, problem with the angularCli apps unload
version 1.12: not able to load the apps

here the log

> single-spa.js:1 Bootstrapping app 'menu' did not resolve or reject within 1000 milliseconds
> single-spa.js:1 Bootstrapping app 'home' did not resolve or reject within 1000 milliseconds
> core.js:3687 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
> single-spa.js:1 Bootstrapping app 'home' did not resolve or reject within 2000 milliseconds
> single-spa.js:1 Bootstrapping app 'home' did not resolve or reject for 4000 milliseconds -- we're no longer going to warn you about it.
> single-spa-angular-cli.js:144 Cannot mount home because that is not bootstraped
> zone.js:675 Error: Uncaught (in promise): [object Undefined]
>     at resolvePromise (zone.js:809)
>     at zone.js:728
>     at single-spa.js:1
>     at ZoneDelegate.invoke (zone.js:388)
>     at Zone.run (zone.js:138)
>     at zone.js:858
>     at ZoneDelegate.invokeTask (zone.js:421)
>     at Zone.runTask (zone.js:188)
>     at drainMicroTaskQueue (zone.js:595)
>     at <anonymous>
> single-spa.js:1 While NOT_MOUNTED, 'home' rejected its lifecycle function promise with a non-Error. This will cause stack traces to not be accurate.
> single-spa.js:1 Uncaught Error: 'home' died in status NOT_MOUNTED: undefined
>     at http://localhost:8080/build/common.js:3697:3958
>     at e.handleAppError (http://localhost:8080/build/common.js:3697:4012)
>     at http://localhost:8080/build/common.js:3697:55379
>     at r (http://localhost:8080/build/common.js:3697:32113)
>     at Generator._invoke (http://localhost:8080/build/common.js:3697:31901)
>     at Generator.t.(anonymous function) [as throw] (http://localhost:8080/build/common.js:3697:32292)
>     at r (http://localhost:8080/build/common.js:3697:3384)
>     at http://localhost:8080/build/common.js:3697:3505
>     at ZoneDelegate.invoke (http://localhost:8080/build/common.js:27180:26)
>     at Zone.run (http://localhost:8080/build/common.js:26930:43)
> single-spa.js:1 singleSpa.start() has not been called, 5000ms after single-spa was loaded. Before start() is called, apps can be declared and loaded, but not bootstrapped or mounted. See https://github.com/CanopyTax/single-spa/blob/master/docs/single-spa-api.md#start
> single-spa.js:1 singleSpa.start() has not been called, 5000ms after single-spa was loaded. Before start() is called, apps can be declared and loaded, but not bootstrapped or mounted. See https://github.com/CanopyTax/single-spa/blob/master/docs/single-spa-api.md#start


I think that the problem is when the single-spa module is in the child app bundle. in my case I´m using a parent app that loads apps as a service, the loader is in the children app and it is bundled using webpack, then it is imported using systemJs and not using a relative reference.  In your examples the loader is using the single-spa module from the parent app ( the app whit the main.js ) because it is imported using a relative reference and it is bundled with the parent app. in this way we loose the power of redeploy separate apps without touch the parent.

**Comment by robinComa** [comment]
Yes I understand the issue...
@joeldenning do you know how to share single spa apps list when it is use inside a loader (ex : getAppNames() loaded by SystemJS?

For your exemple, could you try with : 
```
const LOADER = {
    menu: import('./loaders/menu.js'),
    home: import('./loaders/home.js'),
    app1: import('./loaders/app1.js'),
    help: import('./loaders/help.js')
};

registerApplication('menu', () => LOADER.menu, singleSpaAngularCliRouter.hashPrefix('/**'));
registerApplication('home', () => LOADER.home, singleSpaAngularCliRouter.hashPrefix('/home', true));
registerApplication('app1', () => SystemJS.import("http://localhost:9001/main.js"), singleSpaAngularCliRouter.hashPrefix('/app2',));
registerApplication('app2', () => LOADER.app1, singleSpaAngularCliRouter.hashPrefix('/app1'));
start();
```

Just to be sure the issue is only with the shared single-spa module? tx

**Comment by orlandodemauro** [comment]
@robinComa  thanks again for your help.

I can confirm that app works perfectly with:
```

    const LOADER = {
        menu: import('./menu/loader.js'),
        home: import('./home/loader.js'),
        app2: import('./app2/loader.js')
    };
    
    registerApplication('menu', () => LOADER.menu, singleSpaAngularCliRouter.hashPrefix('/**'));
    registerApplication('home', () => LOADER.home, singleSpaAngularCliRouter.hashPrefix('/home', true));
    registerApplication('app1', () => SystemJS.import("http://localhost:9001/main.js",), singleSpaAngularCliRouter.hashPrefix('/app2'));
    registerApplication('app2', () => LOADER.app2, singleSpaAngularCliRouter.hashPrefix('/app2'));
    start();
```

**Comment by robinComa** [comment]
Ok thank you!
I hope @joeldenning will have a solution for this use case.
I will try with SystemJS loading when as soon as possible.
Regards

**Comment by orlandodemauro** [comment]
@robinComa  thank you so much. do you think I should open an issue in single-spa mentioning this issue and use case?

**Comment by robinComa** [comment]
You are welcome!
Yep good idea!
Thanks!
Don't forget to reference me inside the new issue

**Comment by robinComa** [comment]
Can I close the issue @orlandodemauro? , I merged the PR of @joeldenning , try the new version 0.2.0
Thanks @joeldenning

**Comment by orlandodemauro** [comment]
@robinComa @joeldenning thank you so much. @robinComa  testing now I´ll let you know ASAP, thanks you

**Comment by orlandodemauro** [comment]
@robinComa @joeldenning closing this issue. updating the packages the issue is gone!!!! thank again for your amazing work!!!!
