### ISSUE TITLE
Navigation with path instead of hash

### ISSUE THREAD

**Issue by Kotohitsu** [PlaceMe-SAS/single-spa-angular-cli#7]
I am using Keycloak for authentication, which is using `location.hash` to transfer the tokens. 

The Problem is that the hash value is changed before it can be used in the child application.

So it would be great to use `location.path` instead of `location.hash`.

**Comment by robinComa** [comment]
I try to update with location?path but that's broken my browser ... Any idea?

**Comment by Kotohitsu** [comment]
I've thought about something like this:

``` javascript
registerApplication('menu', () => import('./menu/loader.js'), () => true);
registerApplication('home', () => import('./home/loader.js'), () => location.pathname === "" || location.pathname === "/" || pathPrefix('/home') );
registerApplication('app1', () => import('./app1/loader.js'), pathPrefix('/app1'));

start();

function pathPrefix(prefix) {
    return function(location) {
        return location.pathname.indexOf(`${prefix}`) === 0;
    }
}
```

That's the way they do it in the [single-spa-example](https://github.com/CanopyTax/single-spa-examples/blob/master/src/single-spa-examples.js). But I could not test it yet.

**Comment by robinComa** [comment]
Ok thanks you, I try this week.

**Comment by joeldenning** [comment]
👍 single-spa works with both hash routing and html5 history api routing (pushState/replaceState). A lot of my original examples had hash routing, but I have since updated them to use path routing, since that's the industry standard.

I think that it would be best for single-spa-angular-cli to support either form of routing, but default to path routing. If only one can be supported, path routing is probably the better default.

**Comment by robinComa** [comment]
Hello I fix it on 0.2.3 : 
`singleSpaAngularCliRouter.setPathStrategy('pathname');`

I introduce 2 breaking changes : 
singleSpaAngularCliPlatform.mount('app1', Router).subscribe(({ props, attachUnmount }) => {
  platformBrowserDynamic().bootstrapModule(AppModule).then((module) => {
    attachUnmount(module);
    // Do something with props if you want
    // Ex : module.instance.setSomething(...)
  });
});
It is now the name of the app, not the root selector : app1 replace app1-root
And { props, attachUnmount } to retreive the props

And One new feature on my exemple : 
`registerApplication('help', import('./loaders/help.js'), singleSpaAngularCliRouter.hasParameter('help', 'open'));`
--> has parameter

Hope is ok for you tanks to this fix, fell free to close the issue if it is ok

Bye

**Comment by robinComa** [comment]
sorry @joeldenning I do not use path as default because that's don't work for me, maybe it is my bad but I've not a lot of time to find the solution.
But next time when I will work on the project I will try to fix it and use path as default

**Comment by joeldenning** [comment]
@robinComa sorry to hear that. What were the issues that you ran into with path based routing?

**Comment by robinComa** [comment]
I don't know, i switched quickly because I have no time.
I will try later!

**Comment by Kotohitsu** [comment]
Since version 2.0.0 my loaded apps are not bootstraped anymore. Neither with hash routing nor with path routing.  The files get loaded but the apps are not bootstraped

I've changed the main.ts files of the loaded apps the way you posted.

Do you have any ideas what could be wrong?

``` javascript
import { registerApplication, start } from 'single-spa';
import { singleSpaAngularCliRouter } from 'single-spa-angular-cli';
import 'babel-polyfill';
import 'zone.js';
import './style.scss';

registerApplication('menu', () => import('./menu/loader.js'), singleSpaAngularCliRouter.hashPrefix('/**'));
registerApplication('home', () => import('./home/loader.js'), singleSpaAngularCliRouter.hashPrefix('/home', true) );
registerApplication('app1', () => import('./app1/loader.js'), singleSpaAngularCliRouter.hashPrefix('/app1'));

start();
```

``` javascript
import singleSpaAngularCli from 'single-spa-angular-cli';

const lifecycles = singleSpaAngularCli({
  name: 'menu',
  selector: 'menu-root',
  baseScriptUrl: '/apps/menu',
  styles: ['styles.bundle.css'],
  scripts: ['inline.bundle.js', 'polyfills.bundle.js', 'vendor.bundle.js', 'main.bundle.js', 'scripts.bundle.js']
});

export const bootstrap = [lifecycles.bootstrap];

export const mount = [lifecycles.mount];

export const unmount = [lifecycles.unmount];

export const unload = [lifecycles.unload];

```

**Comment by robinComa** [comment]
I have the same issue when I do the import inside the function, I know is it bad, but for now I do [it](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples#complete-your-single-spa-routes)
Could you try like this?
If your interrested, a new version is [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples#create-an-angular-cli-loader) : 
- It use the location.pathname, location.search and history.pushState
- It simplify the loader
- Reorganise the imports from the namespace
- Allow ng serve for apps inside the poral

**Comment by Kotohitsu** [comment]
If I use `http://localhost:8080`, the loaded apps are still not bootstraped.

If I now reload the page with the path behinde the base URL the sub page scripts are loaded without the outputPath.

**Comment by Kotohitsu** [comment]
I've solved the reload Problem by configuring my node server.

**Comment by robinComa** [comment]
Ok perfect I think you need the fallback history mode.
I close the issue
Thanks for the feedback
