### ISSUE TITLE
Interest in joining in on broader single-spa discussions

### ISSUE THREAD

**Issue by joeldenning** [PlaceMe-SAS/single-spa-angular-cli#9]
@robinComa thanks again for your work on single-spa-angular-cli. It's really lowering the barrier for angular developers to use single-spa. I have updated the single-spa docs to link to your repositories (see CanopyTax/single-spa@1dbafc1 and CanopyTax/single-spa-angular2@8e3accb).

Would you be interested in joining in on some discussions on the future of single-spa and what features are coming down the pipe? Also how we can best promote and document the project. If so, check out https://github.com/CanopyTax/single-spa/projects where we are tracking some of our work. Also there is a slack channel with a group where we have broader discussions about things like this. You can join the channel [here](https://join.slack.com/t/single-spa/shared_invite/enQtMzIwMTcxNTU3ODQyLTM1Y2U1OWMzNTNjOWYyZDBlMDJhN2VkYzk3MDI2NzQ2Nzg0MzMzNjVhNWE2YjVhMTcxNjFkOWYzMjllMmUxMjk) and I will add you to the group once you're in the channel.

**Comment by robinComa** [comment]
Hey, Yes! with pleasure.
I upgrade the demo apps with a new feature : help with : 
registerApplication('help', import('./loaders/help.js'), singleSpaAngularCliRouter.hasParameter('help', 'open'));

Next time I would like to work on a global build and deploy it on gh-pages to have a live demo.

See you next time on slack!
